EXPERIMENT:
  NAME: ""
  TAG: "pair_num_ratio_0.5,alpha_0.5,kdl_16,pear_32,ce_1,seed42,res32x4,shuv1"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "EMD_copy"
  #TYPE: "EMD"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
