EXPERIMENT:
  NAME: ""
  TAG: "pair_num_ratio_0.5,alpha_0.5,kdl_32,pear_16,ce_1,seed42,kendall_1234_1_32_32,res56,res20"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "EMD_copy"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 2.0
