EXPERIMENT:
  NAME: ""
  TAG: "resat,res32x4,res8x4,addkd"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "resAT"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
AT:
  LOSS:
    FEAT_WEIGHT: 1000.

